#!/system/bin/sh
#
# Originally made by @anarkia1976
#	Modified for Xiaomi Mi 3 by @gingerboy92
#


# initialize
echo "[Stellar Kernel] initialize boot script" | tee /dev/kmsg

# disable debugging on some modules
echo "0" > /sys/module/kernel/parameters/initcall_debug;
echo "0" > /sys/module/alarm/parameters/debug_mask;
echo "0" > /sys/module/alarm_dev/parameters/debug_mask;
echo "0" > /sys/module/binder/parameters/debug_mask;
echo "0" > /sys/module/xt_qtaguid/parameters/debug_mask;
echo "[ak kernel] disable debug mask" | tee /dev/kmsg

# Tweaks
echo 2 > /sys/module/msm_hotplug/min_cpus_online;

# Enable ZRAM 
modprobe zram num_devices=4

echo 268435456 > /sys/block/zram0/disksize
echo 268435456 > /sys/block/zram1/disksize
echo 268435456 > /sys/block/zram2/disksize
echo 268435456 > /sys/block/zram3/disksize

mkswap /dev/block/zram0
mkswap /dev/block/zram1
mkswap /dev/block/zram2
mkswap /dev/block/zram3
 
swapon -p 10 /dev/block/zram0
swapon -p 10 /dev/block/zram1
swapon -p 10 /dev/block/zram2
swapon -p 10 /dev/block/zram3
